# Generated by Django 4.2 on 2023-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nabars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nabars',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
